apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: k8s-program
#  - apiVersion: v1
#    kind: PersistentVolumeClaim
#    metadata:
#      namespace: k8s-program
#      name: pvc-usersdb
#    spec:
#      storageClassName: hostpath
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 3Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: usersdb
      namespace: k8s-program
    spec:
      clusterIP: None
      selector:
        app: usersdb-pod
      ports:
        - port: 5432
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: db-secret-credentials
      namespace: k8s-program
      labels:
        app: usersdb-pod
    data:
      # User DB
      POSTGRES_DB: "users"
      # Db user
      POSTGRES_USER: "admin"
      # Db password
      POSTGRES_PASSWORD: "admin1234"
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: usersdb-pod
      namespace: k8s-program
    spec:
      serviceName: usersdb-pod
      selector:
        matchLabels:
          app: usersdb-pod
      replicas: 1
      template:
        metadata:
          labels:
            app: usersdb-pod
        spec:
# it's needed when PVC defined and then volumeClaimTemplates not needed.
#          volumes:
#            - name: pvc-users-storage
#              persistentVolumeClaim:
#                claimName: pvc-usersdb
          containers:
            - name: usersdb-pod
              image: postgres:14.7
              ports:
              - containerPort: 5432
              envFrom:
                - configMapRef:
                    name: db-secret-credentials
              volumeMounts:
                - mountPath: "/var/lib/postgresql/data"
                  name: pvc-users-storage
# it's needed when there is no PVC defined.
      volumeClaimTemplates:
        - metadata:
            name: pvc-users-storage
          spec:
            storageClassName: hostpath
            resources:
              requests:
                storage: 3Gi
            accessModes:
              - ReadWriteOnce
  - apiVersion: v1
    kind: Service
    metadata:
      name: usersapp
      namespace: k8s-program
    spec:
      type: NodePort
      selector:
        app: usersapp-pod
      ports:
        - protocol: "TCP"
          port: 8081
          targetPort: 8081
          nodePort: 32315
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: usersapp-pod
      namespace: k8s-program
    spec:
      selector:
        matchLabels:
          app: usersapp-pod
      replicas: 1
      template:
        metadata:
          labels:
            app: usersapp-pod
            owner: igorpavlyushchik
        spec:
          containers:
            - name: usersapp-container
              image: igorpavlyushchik/users-application:1.0.0
              ports:
                - containerPort: 8081
              env:
                - name: DB_URL
                  value: "jdbc:postgresql://usersdb:5432/users"
                - name: DB_USERNAME
                  value: "admin"
                - name: DB_PASSWORD
                  value: "admin1234"