apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---
apiVersion: v1
kind: Service
metadata:
  name: usersdb
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: usersdb-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdb-pod
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: usersdb-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: usersdb-pod
    spec:
      containers:
      -name: usersdb-container
      image: postgres:14.7
      env:
        -name: POSTGRES_USER
        value: "admin"
        -name: POSTGRES_PASSWORD
        value: "admin1234"
        -name: POSTGRES_DB
        value: "users"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: usersapp
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: usersapp-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapp-pod
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: usersapp-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: usersapp-pod
        owner: igorpavlyushchik
    spec:
      containers:
      -name: usersapp-container
      image: igorpavlyushchik/users-application:1.0.0
      env:
        -name: DB_URL
        value: "jdbc:postgresql://users_db:5432/user"
        -name: DB_USERNAME
        value: "admin"
        -name: DB_PASSWORD
        value: "admin1234"
      ports:
        - containerPort: 8081



